// <auto-generated />
using System;
using Assginment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assginment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200313143815_Database_1")]
    partial class Database_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assginment.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Postid")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Postid");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            User = "Raju",
                            comment = "I don't"
                        },
                        new
                        {
                            id = 2,
                            User = "Raju",
                            comment = "I don"
                        },
                        new
                        {
                            id = 3,
                            User = "Raja",
                            comment = "I"
                        });
                });

            modelBuilder.Entity("Assginment.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Like = 5,
                            Message = "I Love Coding",
                            Users = "Raju"
                        },
                        new
                        {
                            id = 2,
                            Like = 2,
                            Message = "I Coding for Life",
                            Users = "Raj"
                        });
                });

            modelBuilder.Entity("Assginment.Models.Comment", b =>
                {
                    b.HasOne("Assginment.Models.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("Postid");
                });
#pragma warning restore 612, 618
        }
    }
}
